# Generated by Django 4.1.7 on 2023-05-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'id'], include=('title', 'content', 'last_edited'), name='user_idx'),
        ),
    ]
